# directories for bam files
bam_dir: '/mnt/md0/malaria/pf3k_v5/BAM/'
bam_files: '/mnt/md0/malaria/pf3k_v5/senegal_bams.txt'

bam_calls:
  reference_genome: '/mnt/md0/malaria/reference_genome/Pfalciparum.genome.fasta'
  interval_bed: '/mnt/md0/malaria/pf3k_v5/2008Daniels_BarcodePositions_Updated.bed'
  min_read_qual: 20
